### ISSUE TITLE
Nil interaction.responseData for certain content-types

### ISSUE THREAD

**Issue by ksm** [venmo/DVR#21]
Just upgraded to DVR v0.1 and migrated my JSON cassettes using the convert.rb script. Tests started failing because I was not getting JSON data (just a response).

I believe the culprit is https://github.com/venmo/DVR/blob/master/DVR/Interaction.swift#L58. 

DVR checks for `contentType == "application/json"`, but the Content-Type header field can contain more than that. In my case it is `application/json; charset=utf-8`.

Was gonna submit a pull request, but the project refuses to run tests for me due to some Xcode 7 beta 5 silliness: seeing dozens of devices in my device list, then when I choose one and try to run tests from test navigator it says the device is not valid for tests. Building for tests leads to symbol not found errors. :\

One more thing: thank you for DVR. Really liking how it makes a whole category of tests in my app feasible. :sparkling_heart:

**Comment by soffes** [comment]
We should switch that to check for the that as a prefix. Good call!

**Comment by soffes** [comment]
Released [version 0.1.1](https://github.com/venmo/DVR/releases/tag/v0.1.1) with this fix.
