### ISSUE TITLE
Running tests with DVR crashes Xcode

### ISSUE THREAD

**Issue by jordanekay** [venmo/DVR#34]
Seems to be a new issue in 0.2.0. I get either `Invalid request. The request was not found in the cassette.` or `Something has gone horribly wrong.` before Xcode hits a breakpoint and promptly crashes.

**Comment by ayanonagon** [comment]
And you said it works fine for 0.1.4 right? @soffes any ideas as to what’s going on with 0.2.0?

**Comment by mihaigeorgescu-newstore** [comment]
@jordanekay see issue https://github.com/venmo/DVR/issues/33

**Comment by eliperkins** [comment]
Closing as I believe this has been resolved in the latest version of Carthage.
