### ISSUE TITLE
TV OS support

### ISSUE THREAD

**Issue by matthewfx** [venmo/DVR#56]
Please add a support for the tv os.

**Comment by Rep2** [comment]
Also looking for this feature.

Edit: I have added support for tvOS in a fork and it can be fetched using 

> github "Rep2/DVR" "f88d1d2e619457e3b8c675456d3e4ddb1c87846e"

I am new to the Carthage world so check it out before using.

**Comment by loudmouth** [comment]
It looks like there is tvOS support for DVR if installed via Carthage. Not only is there a shared scheme in DVR.xcodeproj "DVR-tvOS", but I have successfully installed DVR via Carthage.

It does not, however, appear that there is a line in the podspec defining the build for tvOS via Cocoapods. This is probably not too difficult to fix.
