### ISSUE TITLE
Update Pod Spec to version 1.0

### ISSUE THREAD

**Issue by ksteigerwald** [venmo/DVR#66]
Created a fork, seems to load fine once updated.

**Comment by FredLoh** [comment]
@ksteigerwald Are you going to open a pull request?

**Comment by ksteigerwald** [comment]
Happy to.

**Comment by ebelinski** [comment]
It has been half a year since version 1.0.0. Is DVR no longer supporting Cocoapods?

**Comment by soffes** [comment]
@eliperkins you're the owner of the pod so I can't push it. Can you either add me or push it? The podspec in `master` is up to date.

**Comment by eliperkins** [comment]
@soffes I'll add you. One sec!

**Comment by eliperkins** [comment]
<img width="783" alt="screen shot 2017-07-20 at 11 48 02 am" src="https://user-images.githubusercontent.com/1051453/28426513-558add82-6d41-11e7-9105-028f81ed33c2.png">

👋 hi friends.

**Comment by ebelinski** [comment]
Woot woot! Thanks guys, that was fast! Now I can use DVR with my favorite dependency manager. 😃
