### ISSUE TITLE
Version 1.3 and 1.3.1 not available on Cocoapods

### ISSUE THREAD

**Issue by loudmouth** [venmo/DVR#88]
Any chance a new release can be pushed to the Cocoapod's specs repo so that a Swift 4.2 version is available?

**Comment by dmiluski** [comment]
Hi @loudmouth , updating now

**Comment by dmiluski** [comment]
Ewwww... ran into this locally. Trying a work-a-round suggested:
https://github.com/CocoaPods/CocoaPods/issues/7708

**Comment by dmiluski** [comment]
Found out CocoaPods beta release addresses the issue mentioned above, then realized I don't have CocoaPods version push permissions. @soffes or @hyperspacemark for permissions?

**Comment by dmiluski** [comment]
Cocoapods release version now available. Closing

**Comment by loudmouth** [comment]
Thanks ya'll!
