### ISSUE TITLE
Swift 5.1 - [Session defaultTaskGroup]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by m-herold** [venmo/DVR#93]
When using Xcode 11 and Swift 5.1 a `dataTask` called with an `URL` as parameter (instead of an `URLRequest`) results in an `NSInvalidArgumentException`:  

`[Session defaultTaskGroup]: unrecognized selector sent to instance`

**Comment by dmiluski** [comment]
Closing now that fix is merged. Thanks @m-herold
